routes/admin.php
<?php

use App\Http\Controllers\Admin\Blogs\BlogsCategoriesController;
use App\Http\Controllers\Admin\Blogs\BlogsController;
use App\Http\Controllers\Admin\EventsController;
use App\Http\Controllers\Admin\GalleriesController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MessagesController;
use App\Http\Controllers\Admin\Morph\FilesController;
use App\Http\Controllers\Admin\Morph\ImagesController;
use App\Http\Controllers\Admin\SermonsController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Organizers\OrganizersController;
use App\Http\Controllers\Services\OgController;
use App\Http\Controllers\Tags\TagsController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Livewire\LivewireController;


Route::prefix('dash')
    ->name('admin.')
    ->group(function () {
        Route::redirect('/', '/dash/login');

        Auth::routes([
            'login' => true,
            'register' => false,
            'verify' => false,
            'reset' => false,
            'confirm' => false
        ]);

        Route::middleware('auth')
            ->group(function () {
                Route::get('/home', [HomeController::class, 'index'])->name('home');

                Route::resource('/sermons', SermonsController::class)->only([
                    'index', 'create', 'edit', 'store'
                ]);
                Route::post('sermons/update/{sermon}', [SermonsController::class, 'update'])->name('sermons.update');

                Route::resource('/events', EventsController::class)->only([
                    'index', 'create', 'show', 'store', 'destroy'
                ]);

                Route::post('/events/{event}/updateEvent', [EventsController::class, 'updateEvent'])->name('events.updateEvent');
                Route::get('/events/{event}/registrations', [EventsController::class, 'registrations'])->name('events.registrations');

                Route::resource('/galleries', GalleriesController::class)->only(['index', 'destroy', 'store']);
                Route::get('/galleries/images', [GalleriesController::class, 'getImages'])->name('galleries.images');
                Route::get('/galleries/articles', [GalleriesController::class, 'articles'])->name('galleries.articles');

                Route::resource('/blogs',  BlogsController::class)->only([
                    'index', 'store', 'create', 'show', 'destroy'
                ]);
                Route::post('blogs/update/{blog}', [BlogsController::class, 'update'])->name('blogs.update');

                Route::get('blogs/{blog}/profile', [BlogsController::class, 'showProfile'])->name('blogs.show.profile');
                Route::get('blogs/{blog}/content', [BlogsController::class, 'showContent'])->name('blogs.show.content');
                Route::get('blogs/{blog}/comments', [BlogsController::class, 'showComments'])->name('blogs.show.comments');

                Route::apiResource('/blog-categories', BlogsCategoriesController::class)->only([
                    'index', 'store', 'destroy'
                ]);

                Route::resource('/messages', MessagesController::class)->only(['index', 'update']);


                Route::apiResource("files", FilesController::class);
                Route::apiResource("images", ImagesController::class);
                Route::apiResource("tags", TagsController::class);
                Route::apiResource("organizers", OrganizersController::class);

                Route::get('settings/profiles', [SettingsController::class, 'profiles'])->name('settings.profiles');
                Route::post('settings/profiles', [SettingsController::class, 'storeProfile']);

                Route::get('settings/church-details', [SettingsController::class, 'churchDetails'])->name('settings.church-details');
                Route::post('settings/church-details', [SettingsController::class, 'storeChurchDetails']);

                Route::get('settings/programmes/items', [SettingsController::class, 'programmesItems'])->name('settings.programmes.items');

                Route::get('settings/programmes', [SettingsController::class, 'programmes'])->name('settings.programmes');
                Route::post('settings/programmes', [SettingsController::class, 'storeProgrammes']);
                Route::delete('settings/programmes/{programme}', [SettingsController::class, 'deleteProgramme'])->name('settings.programmes.destroy');

                Route::get('settings/tags', [SettingsController::class, 'tags'])->name('settings.tags');
                Route::get('settings/organizers', [SettingsController::class, 'organizers'])->name('settings.organizers');
            });

        Route::get('/og-meta', OgController::class)->name('og-meta');
    });



Route::middleware('auth')
    ->prefix('livewire')
    ->group(function () {
        Route::get('', LivewireController::class)->name('livewire');
    });

routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\Guest\ProfileController;
use App\Http\Controllers\Guest\SubscriberController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SermonController;
use App\Http\Controllers\WebPush\WebPushController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('guest.')
    ->group(function () {

        Route::get('/', [HomeController::class, 'index'])->name('home');

        Route::get('/events', [EventController::class, 'index'])->name('events');
        Route::get('/events/{event}/{slug}', [EventController::class, 'show'])->name('events.show');
        Route::post('/events/{event}/registrations', [EventController::class, 'registrations'])->name('events.registrations');

        Route::get('/sermons', [SermonController::class, 'index'])->name('sermons');
        Route::get('/sermons/{sermon}/{slug}', [SermonController::class, 'show'])->name('sermons.show');

        Route::get('/blog', [BlogController::class, 'index'])->name('blog');
        Route::get('/blog/{blog}/{slug}', [BlogController::class, 'show'])->name('blog.show');

        Route::get('/gallery', [GalleryController::class, 'index'])->name('gallery');
        Route::get('/gallery/items', [GalleryController::class, 'items'])->name('gallery.items');

        Route::get('/contact', [ContactController::class, 'index'])->name('contact');
        Route::post('/contact', [ContactController::class, 'storeMessage']);


        Route::get('/profile/{name}', ProfileController::class)->name('app.profiles');

        Route::post('/subscribe', SubscriberController::class)->name('subscribe');

        Route::prefix('web-push')
            ->name('web-push')
            ->group(function () {
                Route::get('/vapid-public-key', [WebPushController::class, 'vapidPublicKey'])->name('.vapid-public-key');
                Route::post('/register', [WebPushController::class, 'register'])->name('.register');
            });
    });

require __DIR__ . '/admin.php';

resources/views/admin/breadcrumb.blade.php
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        @foreach ($items ?? [] as $item)
        <li class="breadcrumb-item h5 {{ $item['active'] ? 'active': '' }}" {{ $item['active'] ? 'aria-current="page"' : '' }}>
            @if (!$item['active'])
                <a href="{{ $item['link'] }}">{{ __($item['name']) }}</a>
            @else
                {{ __($item['name']) }}
            @endif
        </li>
        @endforeach
    </ol>
</nav>
@if (!isset($hr))
<hr>
@endif

resources/views/admin/header.blade.php
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">{{ $app_name }}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100 bg-transparent" type="text" disabled
        placeholder="{{ Auth::user()->name }}" aria-label="Search">
    <livewire:loader />
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" data-no-swup href="{{ route('admin.logout') }}" onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                {{ __('Déconnexion') }}
            </a>
            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</header>

resources/views/admin/main.blade.php
@extends('app-admin')

@section('body')
@include('admin.header')
<div class="container-fluid">
    <div class="row">
        @include('admin.sidebar')

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="mt-4">
                @yield('content')
            </div>
        </main>
    </div>
</div>
@endsection

resources/views/admin/sidebar.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse" g-component="Sidebar">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.home')) ? 'active' : '' }}"
                    href="{{ route('admin.home') }}">
                    <span data-feather="home"></span>
                    {{ __("Profil") }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.sermons.index')) ? 'active' : '' }}"
                    href="{{ route('admin.sermons.index') }}">
                    <span data-feather="file"></span>
                    {{ __("Sermons") }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.events.index')) ? 'active' : '' }}"
                    href="{{ route('admin.events.index') }}">
                    <span data-feather="file"></span>
                    {{ __("Événements") }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.galleries.index')) ? 'active' : '' }}"
                    href="{{ route('admin.galleries.index') }}">
                    <span data-feather="shopping-cart"></span>
                    {{ __("Galerie") }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.blogs.index')) ? 'active' : '' }}"
                    href="{{ route('admin.blogs.index') }}">
                    <span data-feather="bar-chart-2"></span>
                    {{ __("Blog") }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ Str::contains(request()->fullUrl(), route('admin.messages.index')) ? 'active' : '' }}"
                    href="{{ route('admin.messages.index') }}">
                    <span data-feather="layers"></span>
                    {{ __("Messages") }}
                </a>
            </li>
        </ul>
    </div>
</nav>